#!/bin/bash
wordsize=$1
tool=$2
cd $(dirname $0)

if [[ $tool == mingw ]]; then
    if [[ $wordsize == 64 ]]; then
        PATH="/c/msys64/mingw64/bin:$PATH"
    else
        PATH="/c/msys64/mingw32/bin:$PATH"
    fi
    g++ -v
    ./configure
elif [[ $tool == msvc ]]; then
    cl
    CC=cl CXX="cl -TP -GR" ./configure --with-buildrules=msvc ${1+"$@"}
fi
make BUILDRULES=$tool all
./build/test1 *
