#!/usr/bin/env python3
import requests
import sys

r = requests.get('https://qbilt.org')
print(r.status_code)
print(r.text)
for i in sys.argv[1:]:
    print('arg:', i)
print('::set-output name=o1::quack')
