#!/bin/bash
wordsize=$1
tool=$2
cd $(dirname $0)

if [[ $tool == mingw ]]; then
    if [[ $wordsize == 64 ]]; then
        PATH="/c/msys64/mingw64/bin:$PATH"
    else
        PATH="/c/msys64/mingw32/bin:$PATH"
    fi
    g++ a.cc -o a.exe
elif [[ $tool == msvc ]]; then
    cl
    cl -TP -GR -c a.cc
    cl -nologo -O2 -Zi -Gy -EHsc -MD a.obj \
       -link -SUBSYSTEM:CONSOLE -incremental:no -OUT:a.exe
fi
./a.exe
