name: qtest build
on:
  push:
    branches:
    - test/apple-clang
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: ./apple-clang/build
  macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: ./apple-clang/build
