name: qtest build
on:
  push:
    branches:
    - test/basic
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: ./basic/build-linux
  Windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        tool: [msvc, mingw]
        wordsize: [64, 32]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: ./basic/build-windows.bat ${{ matrix.wordsize }} ${{ matrix.tool }}
      - name: Run
        shell: cmd
        run: 'basic\build\test1.exe *'
