name: qtest build
on:
  push:
    branches:
    - test/docker-action
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./docker-action
        id: step1
        with:
          i1: some-input
      - run: "echo output: ${{ steps.step1.outputs.o1 }}"
