name: qtest build
on:
  push:
    branches:
    - test/locale
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: |
          g++ locale/a.cc -o locale/a.out
          locale/a.out
  Windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        tool: [msvc, mingw]
        wordsize: [64, 32]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        shell: cmd
        run: ./locale/build-windows.bat ${{ matrix.wordsize }} ${{ matrix.tool }}
