name: qtest build
on:
  push:
    paths:
      - .github/workflows/path2.yml
      - 'path2/**'
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: grep pass path2/file
