name: path1
on:
  push:
    paths:
      - .github/workflows/path1.yml
      - 'path1/**'
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Build'
        run: grep pass path1/file
