name: slack
on:
  push:
    branches:
    - test/slack
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build'
        run: 'true'
  Slack:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK }}
