name: slack
on:
  push:
    branches:
    - test/slack
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        repository: adventhp/adventhp-devtools
        token: ${{ secrets.CI_TOKEN }}
        path: adventhp-devtools
      - run: adventhp-devtools/slack-notify ${{ secrets.SLACK }}
  Linux:
    runs-on: ubuntu-latest
    needs: Start
    steps:
      - name: 'Build'
        run: 'true'
  Failing:
    runs-on: ubuntu-latest
    needs: Start
    if: ${{ false }}
    steps:
      - name: 'Build'
        run: 'false'
  Skipped:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs:
      - Linux
      - Failing
    steps:
      - run: 'true'
  Canceled:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs: Start
    steps:
      - run: 'sleep 360'
  Slack:
    if: ${{ always() }}
    name: Post Workflow Status To Slack
    needs:
      - Linux
      - Failing
      - Skipped
      - Canceled
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK }}
