name: slack
on:
  push:
    branches:
    - test/slack
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ci-tools/slack-notify --start --url ${{ secrets.SLACK }}
  Linux:
    runs-on: ubuntu-latest
    needs: Start
    steps:
      - name: 'Build'
        run: 'true'
  Failing:
    runs-on: ubuntu-latest
    needs: Start
#    if: ${{ false }}
    steps:
      - name: 'Build'
        run: 'false'
  Skipped:
    runs-on: ubuntu-latest
    if: ${{ false }}
    needs:
      - Linux
      - Failing
    steps:
      - run: 'true'
  Canceled:
    runs-on: ubuntu-latest
#    if: ${{ false }}
    needs: Start
    steps:
      - run: 'sleep 360'
  Slack:
    if: ${{ always() }}
    name: Post Workflow Status To Slack
    needs:
      - Linux
      - Failing
      - Skipped
      - Canceled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ci-tools/slack-notify --complete --url ${{ secrets.SLACK }} --token ${{ secrets.GITHUB_TOKEN }}
