name: slack
on:
  push:
    branches:
    - test/slack
jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: 'Build'
        run: 'true'
  Failing:
    runs-on: ubuntu-latest
    if: ${{ false }}
    steps:
      - name: 'Build'
        run: 'false'
  Skipped:
    runs-on: ubuntu-latest
    needs:
      - Linux
      - Failing
    steps:
      - run: 'true'
  Canceled:
    runs-on: ubuntu-latest
    steps:
      - run: 'sleep 360'
  Slack:
    if: always()
    name: Post Workflow Status To Slack
    needs:
      - Linux
      - Failing
      - Skipped
      - Canceled
    runs-on: ubuntu-latest
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          slack_webhook_url: ${{ secrets.SLACK }}
